#!/usr/bin/env bash
# ===========================================================================
# pi-sync.sh — Bootstrap pi settings, themes, and packages to a new device.
#
# INTENDED AUDIENCE: Written for an LLM (or a human) to read and execute.
# Every step is documented inline.
#
# TOPOLOGY:
#   source  = device with existing ~/.pi/agent/ config (this Pixel 6a)
#   target  = fresh device that needs the same config
#
# COMMANDS:
#   bootstrap   — install from scripts/pi-bootstrap/ in the repo (primary)
#   export      — package current config into a tarball (ad-hoc)
#   import      — install from a tarball or directory (ad-hoc)
#
# WHAT IT SYNCS:
#   ✅  ~/.pi/agent/settings.json    — theme, provider, model, packages list
#   ✅  ~/.pi/agent/themes/*.json    — custom themes (lotek, etc.)
#   ✅  package list from settings   — re-installed via `pi install`
#   ❌  auth.json                    — API keys stay local to each device
#   ❌  chat sessions / history      — local only
#   ❌  models-store.json            — auto-regenerated by pi
#   ❌  node_modules / git repos     — re-created by `pi install`
#
# FILES IN REPO (scripts/pi-bootstrap/):
#   settings.json     — committed so any clone can bootstrap
#   themes/lotek.json — the hotPink+lime theme
#   packages.txt      — pi install list
# ===========================================================================
set -euo pipefail

PI_AGENT_DIR="${HOME}/.pi/agent"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Colors ───────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}✦${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}⚠${NC} $1"; }
err()   { echo -e "${RED}✗${NC} $1"; }

# ===========================================================================
# INSTALL ENGINE — shared by bootstrap and import
#
# Reads a directory with this structure:
#   dir/
#   ├── settings.json        →  ~/.pi/agent/settings.json
#   ├── themes/*.json        →  ~/.pi/agent/themes/
#   └── packages.txt          →  each line installed via `pi install`
#
# BACKUP: existing ~/.pi/agent/ → ~/.pi/agent.bak.<timestamp>
# ===========================================================================
install_from_dir() {
	local SRC="$1"

	if [ ! -d "${SRC}" ]; then
		err "Source directory not found: ${SRC}"
		exit 1
	fi

	# ── Backup existing config ─────────────────────────────────────────────
	if [ -d "${PI_AGENT_DIR}" ]; then
		BACKUP_DIR="${PI_AGENT_DIR}.bak.$(date +%Y%m%d-%H%M%S)"
		cp -r "${PI_AGENT_DIR}" "${BACKUP_DIR}"
		ok "Backed up existing config to ${BACKUP_DIR}"
		info "  Rollback: rm -rf ~/.pi/agent && mv ${BACKUP_DIR} ~/.pi/agent"
	else
		mkdir -p "${PI_AGENT_DIR}"
		warn "No existing ~/.pi/agent/ — starting fresh"
	fi

	# ── Install settings.json ──────────────────────────────────────────────
	if [ -f "${SRC}/settings.json" ]; then
		mkdir -p "${PI_AGENT_DIR}"
		cp "${SRC}/settings.json" "${PI_AGENT_DIR}/settings.json"
		ok "Installed settings.json"
		echo ""
		info "  Settings preview:"
		node -e "
			const s = require('${PI_AGENT_DIR}/settings.json');
			console.log('    theme:       ' + (s.theme || '(default)'));
			console.log('    provider:    ' + (s.defaultProvider || '(not set)'));
			console.log('    model:       ' + (s.defaultModel || '(not set)'));
			console.log('    thinking:    ' + (s.defaultThinkingLevel || '(default)'));
			console.log('    packages:    ' + ((s.packages || []).length + ' installed'));
		"
	else
		warn "No settings.json — skipping"
	fi

	# ── Install themes ─────────────────────────────────────────────────────
	if [ -d "${SRC}/themes" ] && [ "$(ls -A "${SRC}/themes" 2>/dev/null)" ]; then
		mkdir -p "${PI_AGENT_DIR}/themes"
		cp "${SRC}/themes/"*.json "${PI_AGENT_DIR}/themes/"
		ok "Installed theme(s):"
		for f in "${SRC}/themes/"*.json; do
			echo "      $(basename "$f")"
		done
	else
		warn "No themes — skipping"
	fi

	# ── Install packages ───────────────────────────────────────────────────
	if [ -f "${SRC}/packages.txt" ] && [ -s "${SRC}/packages.txt" ]; then
		echo ""
		info "Installing $(wc -l < "${SRC}/packages.txt") package(s)..."
		echo ""
		while IFS= read -r pkg; do
			[ -z "${pkg}" ] && continue
			info "  pi install ${pkg}"
			if npx --yes pi install "${pkg}" 2>&1 | sed 's/^/    /'; then
				ok "Installed: ${pkg}"
			else
				warn "Failed to install: ${pkg} (may need manual setup)"
			fi
			echo ""
		done < "${SRC}/packages.txt"
	else
		warn "No packages.txt — skipping package install"
		info "  You can manually install packages with: pi install <name>"
	fi

	echo ""
	info "╔══════════════════════════════════════════════════════════════╗"
	info "║  INSTALL COMPLETE                                          ║"
	info "║                                                            ║"
	info "║  1. Launch pi on this device:                              ║"
	info "║       pi                                                    ║"
	info "║                                                            ║"
	info "║  2. The lotek theme (and any others) should be active.     ║"
	info "║     If not, check /settings in pi and select it.           ║"
	info "║                                                            ║"
	info "║  3. Verify packages with:                                  ║"
	info "║       pi list                                              ║"
	info "║                                                            ║"
	info "║  4. Rollback if something broke:                           ║"
	info "║     rm -rf ~/.pi/agent && mv ${BACKUP_DIR} ~/.pi/agent   ║"
	info "╚══════════════════════════════════════════════════════════════╝"
	echo ""
}

# ===========================================================================
# BOOTSTRAP — run from a repo clone on the target device
#
# Reads config from the committed scripts/pi-bootstrap/ directory.
# This is the primary entry point: clone the repo, run bootstrap, done.
# ===========================================================================
do_bootstrap() {
	echo ""
	info "╔══════════════════════════════════════════════════════════════╗"
	info "║  pi-sync: BOOTSTRAP — install config from repo             ║"
	info "╚══════════════════════════════════════════════════════════════╝"
	echo ""

	local BOOTSTRAP_DIR="${SCRIPT_DIR}/pi-bootstrap"
	if [ ! -d "${BOOTSTRAP_DIR}" ]; then
		err "Bootstrap directory not found: ${BOOTSTRAP_DIR}"
		err "Make sure you're running this from the repo root."
		err "Expected: scripts/pi-bootstrap/"
		exit 1
	fi

	ok "Bootstrap directory: ${BOOTSTRAP_DIR}"
	echo "  Contents:"
	for f in "${BOOTSTRAP_DIR}"/*; do
		echo "    $(basename "$f")"
	done
	echo ""

	install_from_dir "${BOOTSTRAP_DIR}"
}

# ===========================================================================
# EXPORT — run on the source device
#
# Packages current ~/.pi/agent/ config into a portable tarball.
# ===========================================================================
do_export() {
	local EXPORT_DIR="${SCRIPT_DIR}/pi-config-export"

	echo ""
	info "╔══════════════════════════════════════════════════════════════╗"
	info "║  pi-sync: EXPORT — package config from this device         ║"
	info "╚══════════════════════════════════════════════════════════════╝"
	echo ""

	if [ ! -d "${PI_AGENT_DIR}" ]; then
		err "~/.pi/agent/ not found at ${PI_AGENT_DIR}"
		err "Is pi installed on this machine?"
		exit 1
	fi
	ok "Found ~/.pi/agent/ at ${PI_AGENT_DIR}"

	rm -rf "${EXPORT_DIR}"
	mkdir -p "${EXPORT_DIR}/themes"
	ok "Created export directory: ${EXPORT_DIR}"

	if [ -f "${PI_AGENT_DIR}/settings.json" ]; then
		cp "${PI_AGENT_DIR}/settings.json" "${EXPORT_DIR}/settings.json"
		ok "Exported settings.json"
	fi

	if [ -d "${PI_AGENT_DIR}/themes" ] && [ "$(ls -A "${PI_AGENT_DIR}/themes" 2>/dev/null)" ]; then
		cp "${PI_AGENT_DIR}/themes/"*.json "${EXPORT_DIR}/themes/"
		ok "Exported $(ls "${PI_AGENT_DIR}/themes/"*.json 2>/dev/null | wc -l) theme(s)"
	fi

	node -e "
		const s = require('${PI_AGENT_DIR}/settings.json');
		const pkgs = s.packages || [];
		if (pkgs.length > 0) console.log(pkgs.join('\n'));
	" > "${EXPORT_DIR}/packages.txt" 2>/dev/null && {
		ok "Exported $(wc -l < "${EXPORT_DIR}/packages.txt") package(s)"
	}

	local TARBALL="${SCRIPT_DIR}/pi-config-export.tar.gz"
	tar -czf "${TARBALL}" -C "${SCRIPT_DIR}" "$(basename "${EXPORT_DIR}")"
	ok "Created tarball: ${TARBALL}"
	info "Size: $(du -h "${TARBALL}" | cut -f1)"

	echo ""
	info "╔══════════════════════════════════════════════════════════════╗"
	info "║  EXPORT COMPLETE                                           ║"
	info "║                                                            ║"
	info "║  scp ${TARBALL} user@target:~/   then run:                    ║"
	info "║  ./scripts/pi-sync.sh import ~/pi-config-export.tar.gz     ║"
	info "╚══════════════════════════════════════════════════════════════╝"
	echo ""
}

# ===========================================================================
# IMPORT — run on the target device from a tarball or directory
# ===========================================================================
do_import() {
	local SOURCE="$1"

	echo ""
	info "╔══════════════════════════════════════════════════════════════╗"
	info "║  pi-sync: IMPORT — install from tarball or directory       ║"
	info "╚══════════════════════════════════════════════════════════════╝"
	echo ""

	# If it's a directory, use it directly
	if [ -d "${SOURCE}" ]; then
		ok "Source is a directory: ${SOURCE}"
		install_from_dir "${SOURCE}"
		return
	fi

	# Otherwise treat as tarball
	if [ ! -f "${SOURCE}" ]; then
		err "Not found: ${SOURCE}"
		err "Usage: $0 import <tarball-or-directory>"
		exit 1
	fi
	ok "Tarball: ${SOURCE} ($(du -h "${SOURCE}" | cut -f1))"

	local TEMP_DIR
	TEMP_DIR=$(mktemp -d)
	trap 'rm -rf "${TEMP_DIR}"' EXIT
	tar -xzf "${SOURCE}" -C "${TEMP_DIR}"

	local EXTRACTED_DIR
	EXTRACTED_DIR=$(find "${TEMP_DIR}" -type d -name 'pi-config-export' | head -1)
	if [ -z "${EXTRACTED_DIR}" ]; then
		err "Could not find pi-config-export/ inside the tarball"
		exit 1
	fi
	ok "Extracted to ${EXTRACTED_DIR}"

	install_from_dir "${EXTRACTED_DIR}"
}

# ===========================================================================
# USAGE
# ===========================================================================
print_usage() {
	local SCRIPT
	SCRIPT=$(basename "$0")
	cat << EOF

╔══════════════════════════════════════════════════════════════════════╗
║  pi-sync.sh — Bootstrap pi settings, themes, and packages          ║
║                                                                    ║
║  LLM INSTRUCTIONS:                                                 ║
║                                                                    ║
║  1. Clone the repo on the target device.                           ║
║                                                                    ║
║  2. Run: ./scripts/pi-sync.sh bootstrap                            ║
║     → Reads scripts/pi-bootstrap/ from the repo.                   ║
║     → Backs up existing ~/.pi/agent/, installs settings, themes,   ║
║       and packages via 'pi install'.                               ║
║                                                                    ║
║  3. Launch pi and verify the lotek theme is active.                ║
╚══════════════════════════════════════════════════════════════════════╝

USAGE:
  ${SCRIPT} bootstrap
      Install config from scripts/pi-bootstrap/ in the repo (primary).

  ${SCRIPT} export
      Package current ~/.pi/agent/ into a tarball for ad-hoc transfer.

  ${SCRIPT} import <path>
      Install from a tarball (.tar.gz) or directory.

EXAMPLE:
  ./scripts/pi-sync.sh bootstrap   # fresh clone → ready to go
  ./scripts/pi-sync.sh export      # source device → tarball

EOF
}

# ===========================================================================
# MAIN
# ===========================================================================
case "${1:-help}" in
	bootstrap)
		do_bootstrap
		;;
	export)
		do_export
		;;
	import)
		if [ -z "${2:-}" ]; then
			err "Usage: $0 import <path-to-tarball-or-directory>"
			exit 1
		fi
		do_import "$2"
		;;
	help|--help|-h|"")
		print_usage
		;;
	*)
		err "Unknown command: $1"
		echo "  Usage: $0 bootstrap | export | import <path>"
		exit 1
		;;
esac
